import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell, ChevronLeft, Home, Map, MessageCircle, Plus, Search, User, Heart, Repeat2, BarChart3, MoreHorizontal, Flame, CalendarCheck, Trophy, Send, X, MapPin, Clock3, Check, Gamepad2} from 'lucide-react';
import './styles.css';

const coins={BTC:{name:'Bitcoin',symbol:'₿',color:'#f7931a'},ETH:{name:'Ethereum',symbol:'◆',color:'#627eea'},SOL:{name:'Solana',symbol:'S',color:'#14f195'},XRP:{name:'XRP',symbol:'X',color:'#f5f5f5'}};
const seedPosts=[
  {id:1,user:'고래알람',handle:'@whale_alert',coin:'BTC',time:'12분',text:'비트코인 현물 ETF 순유입이 다시 증가하고 있습니다. 단기 변동성은 크지만 66K 지지 구간을 체크해볼 만합니다.',score:54210,liked:false,likes:82,reposts:21,comments:14},
  {id:2,user:'솔라나킴',handle:'@solkim',coin:'SOL',time:'34분',text:'서울 밋업에서 SOL ↔ BTC 개인 거래 희망합니다. CMC 시세 기준, 소액부터 가능합니다.',score:51980,liked:true,likes:46,reposts:8,comments:19},
  {id:3,user:'차트문어',handle:'@chart_octopus',coin:'ETH',time:'1시간',text:'ETH 일봉 기준 거래량이 붙고 있어요. 여러분은 돌파와 눌림 중 어느 쪽을 기다리시나요?',score:50320,liked:false,likes:124,reposts:31,comments:42}
];

function Logo(){return <div className="logo"><span>KO</span><i>IN</i><b>KORAE</b></div>}
function Coin({type,size='md'}){const c=coins[type];return <span className={`coin ${size}`} style={{'--coin':c.color}}>{c.symbol}</span>}
function Top({title,onBack,action}){return <header className="top">{onBack?<button onClick={onBack} aria-label="뒤로"><ChevronLeft/></button>:<Logo/>}<strong>{title}</strong>{action||<button aria-label="알림"><Bell/><em>3</em></button>}</header>}

function Feed({openProfile}){
 const [tab,setTab]=useState('추천'); const [posts,setPosts]=useState(seedPosts);
 const react=(id,key)=>setPosts(ps=>ps.map(p=>p.id===id?{...p,[key]:key==='liked'?!p.liked:p[key]+1,likes:key==='liked'?p.likes+(p.liked?-1:1):p.likes}:p));
 return <><Top/><div className="seg"><button className={tab==='추천'?'on':''} onClick={()=>setTab('추천')}>추천</button><button className={tab==='코인'?'on':''} onClick={()=>setTab('코인')}>코인 리더보드</button></div>
 {tab==='추천'?<main className="feed"><div className="ticker"><span><Flame/> 지금 뜨는 코인</span>{Object.keys(coins).map((c,i)=><div key={c}><Coin type={c} size="xs"/><b>{c}</b><small className={i===1?'down':''}>{i===1?'−1.8%':`+${[3.2,0,6.7,1.1][i]}%`}</small></div>)}</div>{posts.map(p=><article className="post" key={p.id}>
 <button className="avatar" onClick={openProfile}><Coin type={p.coin}/></button><div className="postbody"><div className="who"><b>{p.user}</b><span>{p.handle} · {p.time}</span><MoreHorizontal/></div><p>{p.text}</p><div className="score"><Gamepad2/> 게임 점수 <b>{p.score.toLocaleString()}</b></div><div className="actions"><button onClick={()=>react(p.id,'comments')}><MessageCircle/>{p.comments}</button><button onClick={()=>react(p.id,'reposts')}><Repeat2/>{p.reposts}</button><button className={p.liked?'liked':''} onClick={()=>react(p.id,'liked')}><Heart fill={p.liked?'currentColor':'none'}/>{p.likes}</button><button><BarChart3/></button></div></div></article>)}</main>:
 <Leaderboard/>}</>
}
function Leaderboard(){const data=[['BTC','고래알람',154210],['SOL','솔라나킴',151980],['ETH','차트문어',148320],['XRP','리플대장',141090]];return <main className="board"><div className="hero"><span>24시간 게임 합산</span><h1>코인 리더보드</h1><p>플레이 점수가 높은 코인이 먼저 노출돼요.</p></div>{data.map((r,i)=><div className="rank" key={r[0]}><strong>{i+1}</strong><Coin type={r[0]}/><div><b>{r[0]}</b><span>{r[1]}</span></div><em>{r[2].toLocaleString()} P</em></div>)}</main>}
function MapPage(){const [selected,setSelected]=useState(null);return <><Top title="마켓" action={<button><Search/></button>}/><main className="mapview"><div className="mapgrid"><div className="road a"/><div className="road b"/><div className="road c"/>{[['SOL',28,32],['BTC',68,24],['ETH',54,68]].map(m=><button key={m[0]} className="pin" style={{left:m[1]+'%',top:m[2]+'%'}} onClick={()=>setSelected(m[0])}><Coin type={m[0]} size="sm"/></button>)}<button className="locate"><MapPin/></button></div><div className="maphead"><b>내 주변 코인 마켓</b><span>활성 마커 12개</span></div>{selected&&<div className="marketcard"><button onClick={()=>setSelected(null)}><X/></button><Coin type={selected}/><div><small>서울 · 1.2km</small><h3>{selected}/BTC 개인 거래</h3><p>CMC 현재가 기준으로 안전하게 거래해요.</p><span><Clock3/> 앞으로 8시간 활성</span></div></div>}</main></>}
function Attendance(){const [checked,setChecked]=useState(false);return <><Top title="출석 현황"/><main className="attendance"><div className="point"><span>나의 포인트</span><strong>{checked?'1,380':'1,360'} P</strong><small>연속 출석 7일째 🔥</small></div><section><div className="sectiontitle"><h2>8월</h2><span>7 / 31일</span></div><div className="calendar">{['일','월','화','수','목','금','토'].map(x=><b key={x}>{x}</b>)}{Array.from({length:35},(_,i)=><span className={i>2&&i<10?'done':i===10?'today':''} key={i}>{i>2?i-2:''}{i>2&&i<10&&<Check/>}</span>)}</div></section><button className="primary" disabled={checked} onClick={()=>setChecked(true)}>{checked?'오늘 출석 완료':'출석하고 +20 P 받기'}</button><div className="mission"><b>오늘의 미션</b><p><Check/> 피드 3개 읽기 <em>+100 P</em></p><p><span/> 게임 5회 플레이 <em>2 / 5</em></p><p><span/> 좋아요 5개 누르기 <em>3 / 5</em></p></div></main></>}
function Profile(){return <><Top title="프로필"/><main className="profile"><div className="cover"/><div className="identity"><div className="bigavatar"><Coin type="BTC"/></div><button>프로필 수정</button><h2>고래알람 <i>✓</i></h2><span>@whale_alert</span><p>시장보다 한 발 빠른 온체인 데이터. BTC를 지지합니다.</p><div><b>142</b> 팔로잉 <b>3,891</b> 팔로워</div></div><div className="level"><Trophy/><div><span>현재 레벨</span><b>돌고래 · Lv. 4</b></div><em>78%</em><i><span/></i><small>다음 레벨까지 2,180 P</small></div><div className="profiletabs"><b>피드</b><span>마커</span><span>댓글</span><span>아이템</span></div>{seedPosts.slice(0,2).map(p=><div className="mini" key={p.id}><p>{p.text}</p><span>{p.time} · ♥ {p.likes}</span></div>)}</main></>}
function Composer({close}){const [coin,setCoin]=useState('BTC');const [text,setText]=useState('');return <div className="sheet"><div className="shade" onClick={close}/><div className="compose"><header><button onClick={close}><X/></button><b>새 피드</b><button className="postbtn" disabled={!text} onClick={close}>게시</button></header><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="코인 사람들과 무엇을 나눌까요?"/><div className="coinpick">{Object.keys(coins).map(c=><button className={coin===c?'on':''} onClick={()=>setCoin(c)} key={c}><Coin type={c} size="xs"/>{c}</button>)}</div><div className="game"><Gamepad2/><div><b>게임으로 피드 점수 올리기</b><span>게시 후 미니게임이 시작돼요</span></div><Check/></div></div></div>}
function App(){const [page,setPage]=useState('home');const [compose,setCompose]=useState(false);const view=useMemo(()=>page==='home'?<Feed openProfile={()=>setPage('profile')}/>:page==='map'?<MapPage/>:page==='attendance'?<Attendance/>:<Profile/>,[page]);return <div className="app">{view}<nav><button className={page==='home'?'on':''} onClick={()=>setPage('home')}><Home/><span>홈</span></button><button className={page==='map'?'on':''} onClick={()=>setPage('map')}><Map/><span>마켓</span></button><button className="create" onClick={()=>setCompose(true)}><Plus/></button><button className={page==='attendance'?'on':''} onClick={()=>setPage('attendance')}><CalendarCheck/><span>출석</span></button><button className={page==='profile'?'on':''} onClick={()=>setPage('profile')}><User/><span>프로필</span></button></nav>{compose&&<Composer close={()=>setCompose(false)}/>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`));
